# constraints_schema.yaml
# JSON Schema (YAML) for constraints catalog files
# ---------------------------------------------------------
# Valida archivos tipo: constraints_vX.Y.yaml
# - version: v\d+\.\d+
# - status: draft | validated | archived
# - constraints: lista de bloques con id único, type y params
# ---------------------------------------------------------

$schema: "https://json-schema.org/draft/2020-12/schema"
title: FBDAM Constraints Catalog
type: object
required: [version, status, constraints]
properties:
  version:
    type: string
    pattern: "^v\\d+\\.\\d+$"
    description: "Semantic-like version (e.g., v1.0)"
  status:
    type: string
    enum: [draft, validated, archived]
  maintainer:
    type: string
  constraints:
    type: array
    minItems: 1
    items:
      type: object
      required: [id, type, params]
      additionalProperties: false
      properties:
        id:
          type: string
          pattern: "^[a-z0-9_]+$"
          description: "Stable, snake_case identifier"
        type:
          type: string
          description: "Constraint handler name in code registry"
          enum:
            - u_link
            - household_floor
            - fairshare_cap_house
            - var_bound
        description:
          type: string
        uri:
          type: string
          format: uri
        params:
          type: object
          description: "Free-form parameter map; validated by handler"
          additionalProperties:
            anyOf:
              - type: string
              - type: number
              - type: boolean
              - type: array
              - type: object
