version: v1
name: Balanced (Equity-Adequacy Trade-off)
description: |
  Policy emphasis: BALANCED

  Balances allocation equity (proportional distribution) with nutritional
  adequacy (minimum outcomes). Represents a middle-ground policy that considers
  both fair distribution and adequate nutrition.
model:
  description: |
    Base model with allocation equity and nutritional adequacy constraints.
    Dials are set to moderate values to balance both dimensions.
  constraints:
    - ref: nutrition_utility_mapping
    - ref: item_supply_limit
    - ref: purchase_budget_limit
    - ref: fairshare_deviation_identity
    - ref: item_equity_aggregate_cap
    - ref: household_equity_aggregate_cap
    - ref: pairwise_equity_cap
    - ref: household_adequacy_floor
    - ref: nutrient_adequacy_floor
    - ref: pairwise_adequacy_floor
  objectives:
    - ref: sum_utility
  dials:
    # Allocation equity dials (balanced)
    alpha: 0.5
    beta: 0.5
    rho: 0.5

    # Nutritional adequacy dials (balanced)
    gamma: 0.5
    kappa: 0.5
    omega: 0.5
