version: v1
name: Balanced (Equity-Adequacy Trade-off)
description: |
  Policy emphasis: BALANCED

  Balances allocation equity (proportional distribution) with nutritional
  adequacy (minimum outcomes). Represents a middle-ground policy that considers
  both fair distribution and adequate nutrition. 

  Meaningful constraints while still flexible.
model:
  description: |
    Base model with allocation equity and nutritional adequacy constraints.
    Dials are set to moderate values to balance both dimensions.
  constraints:
    - ref: nutrition_utility_mapping
    - ref: item_supply_limit
    - ref: purchase_budget_limit
    - ref: fairshare_deviation_identity
    - ref: item_equity_aggregate_cap
    - ref: household_equity_aggregate_cap
    - ref: pairwise_equity_cap
    - ref: household_adequacy_floor
    - ref: nutrient_adequacy_floor
    - ref: pairwise_adequacy_floor
  objectives:
    - ref: sum_utility
  dials:
    # Allocation equity dials (balanced) # 30% max deviation (more noticeable constraint)
    alpha_i: 0.3
    beta_h: 0.3
    gamma_i_h: 0.3

    # Nutritional adequacy dials (balanced) # 60% of mean (more meaningful floor)
    kappa_n: 0.6
    rho_h: 0.6
    omega_n_h: 0.6
