version: v1
name: Gradual Tightening
description: |
  Policy emphasis: TRANSITION

  Mixed dial setting that keeps allocation equity strict while gradually
  tightening nutritional adequacy floors. Useful for sensitivity analysis.
model:
  description: |
    Base model with allocation equity and nutritional adequacy constraints.
    Dials progressively tighten adequacy while maintaining strict proportional
    allocation caps.
  constraints:
    - ref: nutrition_utility_mapping
    - ref: item_supply_limit
    - ref: purchase_budget_limit
    - ref: fairshare_deviation_identity
    - ref: item_equity_aggregate_cap
    - ref: household_equity_aggregate_cap
    - ref: pairwise_equity_cap
    - ref: household_adequacy_floor
    - ref: nutrient_adequacy_floor
    - ref: pairwise_adequacy_floor
  objectives:
    - ref: sum_utility
  dials:
    # Allocation equity dials (strict/medium)
    alpha: 0.1
    beta: 0.1
    rho: 0.5

    # Nutritional adequacy dials (tight)
    gamma: 0.9
    kappa: 0.9
    omega: 0.9
