version: v1
name: Efficiency
model:
  description: |
    Base model with fairness and adequacy constraints. This configuration
    keeps the structure fixed while balancing dials.
  constraints:
    - ref: nutrition_utility_mapping
    - ref: item_supply_limit
    - ref: purchase_budget_limit
    - ref: household_adequacy_floor
    - ref: nutrient_adequacy_floor
    - ref: pairwise_adequacy_floor
    - ref: fairshare_deviation_identity
    - ref: item_equity_aggregate_cap
    - ref: household_equity_aggregate_cap
    - ref: pairwise_equity_cap
  objectives:
    - ref: sum_utility
  model_params:
    budget: 10
  dials:
    alpha: 0.9
    beta: 0.9
    gamma: 0.9
    kappa: 0.1
    rho: 0.1
    omega: 0.1
