version: v1
name: Allocation Equity Priority (Strict Proportional)
description: |
  Strict proportional allocation (allocation equity priority).
  Adequacy floors are relaxed, so some households may have poor
  nutrition outcomes despite receiving their "fair share."
  Demonstrates that proportional allocation ≠ adequate nutrition.

  Use case: When proportional treatment is paramount, even at the cost of
  relaxing nutritional adequacy floors.
model:
  description: |
    Base model with allocation equity and nutritional adequacy constraints.
    Dials are tuned to prioritise proportional allocation equity.
  constraints:
    - ref: nutrition_utility_mapping
    - ref: item_supply_limit
    - ref: purchase_budget_limit
    - ref: fairshare_deviation_identity
    - ref: item_equity_aggregate_cap
    - ref: household_equity_aggregate_cap
    - ref: pairwise_equity_cap
    - ref: household_adequacy_floor
    - ref: nutrient_adequacy_floor
    - ref: pairwise_adequacy_floor
  objectives:
    - ref: sum_utility
  dials:
    # Allocation equity dials (strict)
    alpha: 0.1
    beta: 0.1
    rho: 0.1

    # Nutritional adequacy dials (relaxed)
    gamma: 0.1
    kappa: 0.1
    omega: 0.1
