version: v1
name: Efficiency (Utility Maximisation)
description: |
  Policy emphasis: EFFICIENCY

  Relaxes both allocation equity caps and nutritional adequacy floors so the
  optimiser can maximise total nutritional utility. Suitable for understanding
  the unconstrained efficiency frontier.
model:
  description: |
    Base model with allocation equity and nutritional adequacy constraints.
    Dials are relaxed to emphasise total utility.
  constraints:
    - ref: nutrition_utility_mapping
    - ref: item_supply_limit
    - ref: purchase_budget_limit
    - ref: household_adequacy_floor
    - ref: nutrient_adequacy_floor
    - ref: pairwise_adequacy_floor
    - ref: fairshare_deviation_identity
    - ref: item_equity_aggregate_cap
    - ref: household_equity_aggregate_cap
    - ref: pairwise_equity_cap
  objectives:
    - ref: sum_utility
  model_params:
    budget: 10
  dials:
    # Allocation equity dials (relaxed)
    alpha: 0.9
    beta: 0.9
    rho: 0.9

    # Nutritional adequacy dials (relaxed)
    gamma: 0.1
    kappa: 0.1
    omega: 0.1
