version: v1
name: Efficiency
model:
  description: |
    Base model with fairness and adequacy constraints. This configuration
    keeps the structure fixed while balancing dials.
  constraints:
    - ref: nutrition_utility_mapping
    - ref: item_supply_limit
    - ref: purchase_budget_limit
    - ref: fairshare_deviation_identity
    - ref: item_equity_aggregate_cap
    - ref: household_equity_aggregate_cap
    - ref: pairwise_equity_cap
    - ref: household_adequacy_floor
    - ref: nutrient_adequacy_floor
    - ref: pairwise_adequacy_floor
  objectives:
    - ref: sum_utility
  dials:
    alpha: 1
    beta: 1
    rho: 1
    gamma: 0.1
    kappa: 0.1
    omega: 0.1
