version: v1
name: Fairness (Proportional Allocation)
description: |
  Policy emphasis: ALLOCATION EQUITY

  Enforces strict proportional allocation (fair-share) with minimal deviation
  in item distribution. Households receive quantities proportional to their
  size (w[h]).

  Use case: When proportional treatment is paramount, even at the cost of
  relaxing nutritional adequacy floors.
model:
  description: |
    Base model with allocation equity and nutritional adequacy constraints.
    Dials are tuned to prioritise proportional allocation equity.
  constraints:
    - ref: nutrition_utility_mapping
    - ref: item_supply_limit
    - ref: purchase_budget_limit
    - ref: fairshare_deviation_identity
    - ref: item_equity_aggregate_cap
    - ref: household_equity_aggregate_cap
    - ref: pairwise_equity_cap
    - ref: household_adequacy_floor
    - ref: nutrient_adequacy_floor
    - ref: pairwise_adequacy_floor
  objectives:
    - ref: sum_utility
  dials:
    # Allocation equity dials (strict)
    alpha: 0.1
    beta: 0.1
    rho: 0.1

    # Nutritional adequacy dials (relaxed)
    gamma: 0.1
    kappa: 0.1
    omega: 0.1
